apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "app-init.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "app-init.labels" . | nindent 4 }}
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "app-init.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["echo"]
          args: ["***here you need dotnet ef or efbundle***"]
          {{- with .Values.resources }}
          resources:
          {{ toYaml . | nindent 12 }}
          {{- end }}
      restartPolicy: {{ .Values.job.restartPolicy }}