# Default values for mts-sre-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global config
global:
  env:
  #"ASPNETCORE_ENVIRONMENT": "Develop"
  #"ASPNETCORE_FORWARDEDHEADERS_ENABLED": "true"

# config for app-api 
app-api:
  replicaCount: 1

  env:
    "db_username": ""
    "db_password": ""
    "db_host": ""
    "ASPNETCORE_URLS": "http://+:3003"
    "Serilog__MinimumLevel__Default": "Information"

  image:
    repository: ghcr.io/ldest/sre-course/api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "f0135e1"

  service:
    type: ClusterIP
    port: 3003

  ingress:
    enabled: true
    className: "nginx"
    hosts:
    - host: mts-sre.app
      paths:
      - path: /
        pathType: ImplementationSpecific

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

  livenessProbe:
    httpGet:
      path: /healthz/live
      port: http
    initialDelaySeconds: 20
    periodSeconds: 30
    timeoutSeconds: 60

  readinessProbe:
    httpGet:
      path: /healthz/ready
      port: http
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 60

  autoscaling:
    enabled: false

  serviceAccount:
    name: student72
    create: false

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}


# config for app-init
app-init:
  replicaCount: 1

  env:
    "ASPNETCORE_URLS": "http://+:3003"

  image:
    repository: ghcr.io/ldest/sre-course/api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "f0135e1"

  job:
    ## Should the job be rescheduled on the same node if it fails, or just stopped
    restartPolicy: Never

  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 64Mi

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  serviceAccount:
    create: false

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  volumes: []
  volumeMounts: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
