---
{{- $passwordValue := (randAlphaNum 16) | b64enc | quote }}
{{- $usernameValue := (randAlphaNum 16) | b64enc | quote }}
{{- $dbHostValue := (randAlphaNum 16) | b64enc | quote }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-api.fullname" . }}-cred
type: Opaque
data:
  {{- if .Values.env.db_username }}
  username: {{ .Values.env.db_username | b64enc }}
  {{- else }}
  username: {{ $usernameValue }}
  {{- end }}
  {{- if .Values.env.db_password }}
  password: {{ .Values.env.db_password | b64enc }}
  {{- else }}
  password: {{ $passwordValue }}
  {{- end }}
  {{- if .Values.env.db_host }}
  db_host: {{ .Values.env.db_host | b64enc }}
  {{- else }}
  db_host: {{ $dbHostValue }}
  {{- end }}